name: 📝 General Issue
description: Bug Report, Feature Request oder Frage einreichen
title: "[ISSUE] "
labels: ["needs-triage"]
assignees: []

body:
  - type: dropdown
    id: issue_type
    attributes:
      label: Typ des Issues
      description: Was für eine Art von Issue willst du melden?
      options:
        - 🐛 Bug Report
        - ✨ Feature Request
        - ❓ Frage
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      description: Erkläre das Problem oder die Idee so genau wie möglich.
      placeholder: |
        Beschreibe hier:
        - Was wolltest du erreichen?
        - Was ist stattdessen passiert?
        - Warum ist das relevant?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Screenshots/Fehlermeldungen
      description: Alles, was hilft, den Fehler oder das Verhalten zu verstehen.
      placeholder: |
        ```bash
        Traceback (most recent call last):
          ...
        ```
    validations:
      required: false
