name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest 
          # pytest sucht alle Dateien im aktuellen Verzeichnis und in Unterverzeichnissen, die mit test_ anfangen oder enden.
          # In diesen Dateien sucht es dann nach Funktionen, die mit test_ anfangen, um sie als Tests zu erkennen!
